# https://travis-ci.org/#!/phlax/envoy-examples

dist: bionic

env:
  jobs:
    - ENVOYDEV_UMASK=027 ENVOY_REPO="-b verify-examples-reprise--testing https://github.com/phlax/envoy"

script:
  - shellcheck -x run-tests-as-envoydev
  - export COMPOSE_FILE=./composition/docker-compose.yml
  - docker-compose up --build -d
  - docker-compose logs
  - docker-compose exec -u envoydev envoy-examples run-envoy-example-tests
