#!/bin/bash -e


echo -e "\n> Install system requirements (curl, git, jq, python3-pip, sudo)"
apt update
apt install -y -qq --no-install-recommends curl git jq python3-pip sudo

echo -e "\n> Install python requirements (docker-compose pip setuptools)"
pip3 install -U pip setuptools
pip3 install -U docker-compose

echo -e "\n> Create demo user (envoydev)"
useradd \
    -m \
    -d /home/envoydev \
    -k /etc/skel \
    -s /bin/bash \
    envoydev

echo -e "\n> Add envoydev to docker group"
gpasswd -a envoydev docker

echo -e "\n> Run test script as envoydev..."
cd /home/envoydev
sudo ENVOYDEV_UMASK="$ENVOYDEV_UMASK" ENVOY_REPO="$ENVOY_REPO" -u envoydev -i run-tests-as-envoydev
