#

version: "2.4"
services:
  app:
    image: busybox
    depends_on:
      envoy-examples:
        condition: service_healthy

  envoy-examples:
    build:
      context: ../context
    tty: true
    privileged: true

    environment:
      - ENVOYDEV_UMASK
      - ENVOY_REPO

    volumes:
      - ${PWD}/run-tests-as-envoydev:/usr/local/bin/run-tests-as-envoydev

      # persist docker images etc
      - ${PWD}/docker:/var/lib/docker
