#

version: "2.4"
services:
  app:
    image: busybox
    depends_on:
      envoy-examples:
        condition: service_healthy

  envoy-examples:
    image: phlax/docker-in-docker
    tty: true
    privileged: true

    environment:
      - ENVOYDEV_UMASK
      - ENVOY_REPO

    volumes:
      - ${PWD}/run-envoy-examples:/usr/local/bin/run-envoy-examples
      - ${PWD}/run-tests-as-envoydev:/usr/local/bin/run-tests-as-envoydev

      # persist docker images etc
      - ${PWD}/docker:/var/lib/docker

      # systemd requirement
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

    tmpfs:
      # systemd requires these to be on tmpfs
      - /run
      - /run/lock
      - /tmp
