#!/bin/bash

ENVOYDEV_UMASK=${ENVOYDEV_UMASK:-027}
ENVOY_REPO=${ENVOY_REPO:-https://github.com/envoyproxy/envoy}


clone_envoy_repo () {
    local git_args
    read -ra git_args <<< "$ENVOY_REPO"
    echo "Clone envoy repository ($ENVOY_REPO)"
    git clone "${git_args[@]}"
}

umask "$ENVOYDEV_UMASK"
clone_envoy_repo
cd envoy
./ci/verify_examples.sh
